### ISSUE TITLE
Doesn't compile in Arduino 1.8.15 (not sure about other versions)

### ISSUE THREAD

**Issue by voroshkov** [goebish/nrf24_multipro#44]
I download archive and open nRF24_multipro.ino --> Arduino IDE opens.
Click compile icon in Arduino IDE  --> get multiple errors "xxx was not declared in this scope"

**Comment by voroshkov** [comment]
Thanks for the project anyway! :)

**Comment by ZeliangSu** [comment]
I have the same issue on Mac OS Mojave.

**Comment by ZeliangSu** [comment]
@voroshkov I got the same problem but I figured it out. In my case, the code sketch exploded the memory of the Arduino. I deleted all the comments and it works like a charm. Hope it's useful for you.

**Comment by SteveQUT** [comment]
Can confirm also have this issue.

**Comment by goebish** [comment]
Seems like the last Arduino IDE doesn't appreciate long comments at the beginning of the main file.
Download / checkout the project again, it should be fixed now.
